INSERT INTO `users` (`username`, `password`, `name`, `nip_user`, `wilayah`, `role`, `status`) 
VALUES ( 
('keninkaning_fadhila', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Kenikaning Fadhila', '', '', 'Pemakai', 'Aktif'),
('suryati', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Suryati', '', '', 'Pemakai', 'Aktif'),
('sukarno', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Sukarno', '', '', 'Pemakai', 'Aktif'),
('wilis', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Wilis R', '', '', 'Pemakai', 'Aktif'),
('retno_sri', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Retno Sri Mastuti', '', '', 'Pemakai', 'Aktif'),
('lina_umboro', '$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6', 'Lina Umboro', '', '', 'Pemakai', 'Aktif'),
('sumarmi','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sumarmi', '', '', 'Pemakai', 'Aktif'),
('siti_minasari','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Siti Minasari', '', '', 'Pemakai', 'Aktif'),
('tuminah','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Tuminah', '', '', 'Pemakai', 'Aktif'),
('eri_taufikrahman','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Eri Taufikrahman', '', '', 'Pemakai', 'Aktif'),
('endang_supriyani','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Endang Supriyani', '', '', 'Pemakai', 'Aktif'),
('sam_budiono','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sam Budiono', '', '', 'Pemakai', 'Aktif'),
('dwi_susanti','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Dwi Susanti', '', '', 'Pemakai', 'Aktif'),
('diah_lestari_r','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Diah Lestari R', '', '', 'Pemakai', 'Aktif'),
('haryati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Haryati', '', '', 'Pemakai', 'Aktif'),
('dwi_sartika_w','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Dwi Sartika W', '', '', 'Pemakai', 'Aktif'),
('vian','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Vian', '', '', 'Pemakai', 'Aktif'),
('mayangkarti','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Mayangkarti', '', '', 'Pemakai', 'Aktif'),
('istiyati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Istiyati', '', '', 'Pemakai', 'Aktif'),
('ops_kia_kesmas','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS KIA Kesmas', '', '', 'Pemakai', 'Aktif'),
('hermawan_s_n','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Hermawan S N', '', '', 'Pemakai', 'Aktif')		,				
('sastrawati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sastrawati', '', '', 'Pemakai', 'Aktif')			,			
('sumarno','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sumarno', '', '', 'Pemakai', 'Aktif')				,		
('bayu_ariesetyawan','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Bayu Ariesetyawan', '', '', 'Pemakai', 'Aktif'),						
('kusmayadi','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Kusmayadi', '', '', 'Pemakai', 'Aktif')				,		
('wakijan','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Wakijan', '', '', 'Pemakai', 'Aktif')					,	
('ops_yankes_i','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS Yankes I', '', '', 'Pemakai', 'Aktif')			,			
('nanik_puji_handaya','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Nanik Puji Handayani', '', '', 'Pemakai', 'Aktif'),						
('yohana_s','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Yohana S', '', '', 'Pemakai', 'Aktif')						,
('dr.kurnia_rizqa_ak','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','dr.Kurnia Rizqa Akbar', '', '', 'Pemakai', 'Aktif'),						
('hanif_pandu_s','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Hanif Pandu S', '', '', 'Pemakai', 'Aktif')			,			
('rini_s','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Rini S', '', '', 'Pemakai', 'Aktif')						,
('sri_sumarni','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sri Sumarni', '', '', 'Pemakai', 'Aktif')			,			
('amin_rofii','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Amin Rofii', '', '', 'Pemakai', 'Aktif')				,		
('anggun_desita','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Anggun Desita', '', '', 'Pemakai', 'Aktif')		,				
('eko_p_h','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Eko P H', '', '', 'Pemakai', 'Aktif')					,	
('aditya_sadewo','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Aditya Sadewo', '', '', 'Pemakai', 'Aktif')		,				
('mamat_supriono','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Mamat Supriono', '', '', 'Pemakai', 'Aktif')		,				
('jatmiko','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Jatmiko', '', '', 'Pemakai', 'Aktif')					,	
('agus_mulyanto','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Agus Mulyanto', '', '', 'Pemakai', 'Aktif')		,				
('asnawi','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Asnawi', '', '', 'Pemakai', 'Aktif')						,
('sarjono_(hastanto)','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Sarjono (hastanto)', '', '', 'Pemakai', 'Aktif'),						
('ops','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS', '', '', 'Pemakai', 'Aktif')						,
('ledhia_e','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Ledhia E', '', '', 'Pemakai', 'Aktif')				,		
('yuli_kurniasih','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Yuli Kurniasih', '', '', 'Pemakai', 'Aktif')	,					
('erna_handayani','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Erna Handayani', '', '', 'Pemakai', 'Aktif')	,					
('udjianti','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Udjianti', '', '', 'Pemakai', 'Aktif')				,		
('m_al_irsyad','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','M Al Irsyad', '', '', 'Pemakai', 'Aktif')		,				
('siwi_p','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Siwi P', '', '', 'Pemakai', 'Aktif')					,	
('ana_aszana','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Ana Aszana', '', '', 'Pemakai', 'Aktif')			,			
('maghdarini','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Maghdarini', '', '', 'Pemakai', 'Aktif')			,			
('heri_wibowo','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Heri Wibowo', '', '', 'Pemakai', 'Aktif')		,				
('romi_hariyanto','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Romi Hariyanto', '', '', 'Pemakai', 'Aktif')	,					
('ops','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS', '', '', 'Pemakai', 'Aktif')						,
('andi_w','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Andi W', '', '', 'Pemakai', 'Aktif')					,	
('lies_sunarliawati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Lies Sunarliawati', '', '', 'Pemakai', 'Aktif'),						
('hasanudin','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Hasanudin', '', '', 'Pemakai', 'Aktif')				,		
('wahyoto','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Wahyoto', '', '', 'Pemakai', 'Aktif')					,	
('ops_yankes_iii','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS Yankes III', '', '', 'Pemakai', 'Aktif')		,				
('mutia_galuh_m','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Mutia Galuh M', '', '', 'Pemakai', 'Aktif')		,				
('deny_novani','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Deny Novani', '', '', 'Pemakai', 'Aktif')			,			
('siti_endah_w','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Siti Endah W', '', '', 'Pemakai', 'Aktif')			,			
('wahyu_kesmas','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Wahyu Kesmas', '', '', 'Pemakai', 'Aktif')			,			
('frederico_m_cabral','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Frederico M Cabral', '', '', 'Pemakai', 'Aktif'),						
('deby_wijaya','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Deby Wijaya', '', '', 'Pemakai', 'Aktif')				,		
('susyanto','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Susyanto', '', '', 'Pemakai', 'Aktif')						,
('nina_risqiana','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Nina Risqiana', '', '', 'Pemakai', 'Aktif')			,			
('dr._syska_maolana','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','dr. Syska Maolana', '', '', 'Pemakai', 'Aktif')	,					
('febriana_larasati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Febriana Larasati', '', '', 'Pemakai', 'Aktif')	,					
('supriyono','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Supriyono', '', '', 'Pemakai', 'Aktif')					,	
('juwarti','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Juwarti', '', '', 'Pemakai', 'Aktif')						,
('wiwid_a_h','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Wiwid A H', '', '', 'Pemakai', 'Aktif')					,	
('ilham_s','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Ilham S', '', '', 'Pemakai', 'Aktif')						,
('taufik_hidayat','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Taufik Hidayat', '', '', 'Pemakai', 'Aktif')			,			
('joko_wuryanto','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Joko Wuryanto', '', '', 'Pemakai', 'Aktif')			,			
('retno_septiani','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Retno Septiani', '', '', 'Pemakai', 'Aktif')			,			
('eni_setiawati','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Eni Setiawati', '', '', 'Pemakai', 'Aktif')			,			
('dani_miarso','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Dani Miarso', '', '', 'Pemakai', 'Aktif')				,		
('satria','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Satria', '', '', 'Pemakai', 'Aktif')						,
('aning','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Aning', '', '', 'Pemakai', 'Aktif')						,
('ops_yankes_ii','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','OPS Yankes II', '', '', 'Pemakai', 'Aktif')		,				
('ida_uli_basa','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Ida Uli Basa', '', '', 'Pemakai', 'Aktif')			,			
('motor_ambulance_he','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Motor Ambulance Hebat', '', '', 'Pemakai', 'Aktif'),						
('motor_ambulance_si','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Motor Ambulance Siaga', '', '', 'Pemakai', 'Aktif'));						

INSERT INTO `users` (`username`, `password`, `name`, `nip_user`, `wilayah`, `role`, `status`) 
VALUES
('dr.mochamad_abdul_hakam','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','dr.Mochamad Abdul Hakam,Sp.PD', '', '', 'Pemakai', 'Aktif')						,	
('dr.lilik_faridah','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','dr.Lilik Faridah', '', '', 'Pemakai', 'Aktif')							,
('drg_rahma_defi,m.kes','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','drg Rahma Defi,M.Kes', '', '', 'Pemakai', 'Aktif')					,		
('endah_emayanti,skm.msi','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Endah Emayanti,SKM.MSi', '', '', 'Pemakai', 'Aktif')				,			
('dr.nugroho_edy_r_m.kes','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','dr.Nugroho Edy R M.Kes', '', '', 'Pemakai', 'Aktif')				,			
('nur_dian_rahmawati_ns.m','$2y$10$pTH9gnNmG0XeA4lrtI0z2uMuWEMA6x8MCHRnNE6AaGutdTSb9moM6','Nur Dian Rahmawati Ns.MPH', '', '', 'Pemakai', 'Aktif')			;				